### ISSUE TITLE
First example: TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'

### ISSUE THREAD

**Issue by nschloe** [matplotlib/viscm#36]
When trying to perform the very first example in the readme,
```
python -m viscm view jet
```
I'm getting
```
TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'
```
This is with numpy 1.14.0.

**Comment by lrq3000** [comment]
Same error here with same example...

**Comment by lrq3000** [comment]
Ok I tried with both viscm 0.6, 0.7 and the git version. It works with git version, so it seems this bug was already fixed (but not yet pushed to pypi, maybe it would be a good time to do so?).

I recently updated matplotlib and most of my scientific packages, this error might be related to the newer versions of these packages.

**Comment by endolith** [comment]
Still a problem with Anaconda + `pip install viscm`

Works after `pip install -U git+https://github.com/matplotlib/viscm`

**Comment by stefanv** [comment]
I cannot replicate with latest viscm + matplotlib.  Closing, please re-open if this is still a problem.
